[package]
name = "publish"
version.workspace = true
edition.workspace = true

[dependencies]
terrarium-core = { path = "../terrarium-core" }
runtime-api = { path = "../runtime-api" }
tar = { workspace = true }
zstd = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }